title: "Governators Robot2026 Post-Season Docs"
description: "Docs for 3361's robot for the 2026 Post-Season"
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

url: "https://governators.github.io"
baseurl: "/Robot2026---Post-Season"

plugins:
  - jekyll-remote-theme

# Build settings
exclude:
  - README.md
